[tool.poetry]
name = "poc_pytest"
version = "0.1.0"
description = "POC for pytest library and poetry"
authors = ["Emax <maxadau@gmail.com>"]

[tool.poetry.dependencies]
python = "3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
